# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sebastian Funk
email: sebastian.funk@lshtm.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Sebastian Funk's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sbfnk.github.io" # the base hostname & protocol for your site
twitter_username: sbfnk
github_username:  sbfnk
scholar_profile: yOo8u2gAAAAJ

# Build settings
markdown: kramdown

google_analytics: UA-79628714-1
